/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { CompletionClientPolicy, CompletionFrame, CompletionRequest } from '@kermanx/dsh-composer-completion/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$636f6d706f736572436f6d706c6574696f6e {
    complete: (request: CompletionRequest, signal?: AbortSignal) => AsyncIterable<CompletionFrame>
    policy: () => Promise<RemoteResult<CompletionClientPolicy>>
  }
  interface TypertRemoteMap {
    'composerCompletion/complete': (request: CompletionRequest, signal?: AbortSignal) => AsyncIterable<CompletionFrame>
    'composerCompletion/policy': () => Promise<RemoteResult<CompletionClientPolicy>>
  }
  interface TypertRemoteNamespaceMap {
    'composerCompletion': TypertRemoteNamespace$636f6d706f736572436f6d706c6574696f6e
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
