/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _kermanx_dsh_composer_completion_composerCompletion_complete_parameter_0$schema = z.object({
  'sessionId': z.string().readonly(),
  'draft': z.string().readonly(),
})
const _kermanx_dsh_composer_completion_composerCompletion_complete_result$schema = z.union([z.object({
  'type': z.literal("update").readonly(),
  'context': z.object({
  'anchorMessageId': z.string().readonly(),
  'model': z.string().readonly(),
  'promptVersion': z.string().readonly(),
}).readonly(),
  'text': z.string().readonly(),
}), z.object({
  'type': z.literal("done").readonly(),
  'context': z.object({
  'anchorMessageId': z.string().readonly(),
  'model': z.string().readonly(),
  'promptVersion': z.string().readonly(),
}).readonly(),
  'text': z.string().readonly(),
})])
const _kermanx_dsh_composer_completion_composerCompletion_policy_result$schema = z.object({
  'enabled': z.boolean().readonly(),
  'model': z.string().readonly(),
  'promptVersion': z.string().readonly(),
  'debounceMs': z.number().readonly(),
  'minPrefixCharacters': z.number().readonly(),
  'requestTimeoutMs': z.number().readonly(),
  'maxOutputCharacters': z.number().readonly(),
  'cacheEntries': z.number().readonly(),
  'cacheTtlMs': z.number().readonly(),
})

export const TYPERT = {
  package: '@kermanx/dsh-composer-completion',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@kermanx/dsh-composer-completion#composerCompletion/complete',
      service: 'composerCompletion',
      namespace: 'composerCompletion',
      method: 'complete',
      mode: 'stream',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@kermanx/dsh-composer-completion/types#CompletionRequest',
            schema: _kermanx_dsh_composer_completion_composerCompletion_complete_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@kermanx/dsh-composer-completion/types#CompletionFrame',
        schema: _kermanx_dsh_composer_completion_composerCompletion_complete_result$schema,
      },
      sourceLocation: {"file":"packages/composer-completion/src/index.ts","line":151,"column":3},
    },
    {
      id: '@kermanx/dsh-composer-completion#composerCompletion/policy',
      service: 'composerCompletion',
      namespace: 'composerCompletion',
      method: 'policy',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@kermanx/dsh-composer-completion/types#CompletionClientPolicy',
        schema: _kermanx_dsh_composer_completion_composerCompletion_policy_result$schema,
      },
      sourceLocation: {"file":"packages/composer-completion/src/index.ts","line":135,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "description": "Host service backing the generated `remote.composerCompletion` namespace.",
        "summary": "Host service backing the generated `remote.composerCompletion` namespace.",
        "tags": [],
        "jsDoc": "/** Host service backing the generated `remote.composerCompletion` namespace. */",
        "key": "composerCompletion",
        "exportName": "ComposerCompletionService",
        "members": [
          {
            "kind": "method",
            "name": "policy",
            "signature": "@Remote('policy') policy(): CompletionClientPolicy",
            "summary": "Return the browser policy paired with this Host generation policy.",
            "jsDoc": "/** Return the browser policy paired with this Host generation policy. */"
          },
          {
            "kind": "method",
            "name": "complete",
            "signature": "@Remote({ mode: 'stream' }) complete(request: CompletionRequest, signal: AbortSignal): AsyncIterable<CompletionFrame>",
            "summary": "Stream user-input suffix snapshots without mutating Session history.",
            "jsDoc": "/** Stream user-input suffix snapshots without mutating Session history. */"
          }
        ],
        "types": [
          {
            "name": "CompletionClientPolicy",
            "declaration": "export interface CompletionClientPolicy {\n    readonly enabled: boolean;\n    readonly model: string;\n    readonly promptVersion: string;\n    readonly debounceMs: number;\n    readonly minPrefixCharacters: number;\n    readonly requestTimeoutMs: number;\n    readonly maxOutputCharacters: number;\n    readonly cacheEntries: number;\n    readonly cacheTtlMs: number;\n}"
          },
          {
            "name": "CompletionContext",
            "declaration": "export interface CompletionContext {\n    readonly anchorMessageId: string;\n    readonly model: string;\n    readonly promptVersion: string;\n}"
          },
          {
            "name": "CompletionFrame",
            "declaration": "export type CompletionFrame = { readonly type: 'update'; readonly context: CompletionContext; readonly text: string; } | { readonly type: 'done'; readonly context: CompletionContext; readonly text: string; };"
          },
          {
            "name": "CompletionRequest",
            "declaration": "export interface CompletionRequest {\n    readonly sessionId: string;\n    readonly draft: string;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
